print("=== aplikasi biodata ===")
name =  input("masukan nama :")
gender =  input("masukan gender :")
tanggal_Lahir = input("masukan tanggal lahir :")
hobi = input("masukan hobi :")

print("nama :", name)
print("gender :", gender)
print("tanggal lahir :",tanggal_Lahir)
print("hobi :", hobi)